apiVersion: v1
kind: Service
metadata:
  name: complete-prodcution-e2e-pipeline-svc
spec:
  type: NodePort
  selector:
    app: complete-prodcution-e2e-pipeline-app
  ports:
    - port: 80
      targetPort: 8080
